branch-defaults:
  default:
    environment: brithon-dev
global:
  application_name: My First Elastic Beanstalk Application
  default_ec2_keyname: brithon_wp
  default_platform: 64bit Amazon Linux 2015.03 v1.3.2 running PHP 5.5
  default_region: us-east-1
  profile: null
  sc: null
